[package]
name = "dark-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
dark_assets.workspace = true
dark_combat.workspace = true
dark_life.workspace = true
dark_physics.workspace = true
dark_render.workspace = true
dark_sim.workspace = true
dark_spine.workspace = true
dark_sprite.workspace = true
dark_story.workspace = true
dark_view.workspace = true
dark_world.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
glam.workspace = true
pollster.workspace = true
rfd.workspace = true
ron.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true
winit.workspace = true
image.workspace = true
