[package]
name = "dark_audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
glam.workspace = true
libloading.workspace = true
thiserror.workspace = true
tracing.workspace = true
