[package]
name = "dark_view"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
dark_assets.workspace = true
dark_physics.workspace = true
dark_render.workspace = true
dark_sprite.workspace = true
dark_world.workspace = true
glam.workspace = true
tracing.workspace = true
