[package]
name = "dark_render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
pollster.workspace = true
thiserror.workspace = true
tracing.workspace = true
wgpu.workspace = true
winit.workspace = true
bytemuck.workspace = true
cosmic-text.workspace = true
dark_sprite.workspace = true
glam.workspace = true

[dev-dependencies]
naga.workspace = true
